### ISSUE TITLE
Where is the book?

### ISSUE THREAD

**Issue by ghost** [dom96/nim-in-action-code#1]
I see some example code but where it the complete work?

**Comment by dom96** [comment]
[You need to purchase it.](https://manning.com/books/nim-in-action?a_aid=niminaction&a_bid=78a27e81)

**Comment by ghost** [comment]
You're the author right? Just paste it here, then everyone with an internet connection will be able to read it. Unless you didn't write it so others could read it and learn nim. Even if you want to make money, your best bet is to distribute it on the internet, obtain recognition, spread the nim languague as far and wide as possible, then charge big consulting fees to ventures that want your expertise on deploying solutions that use nim. The copyright thing is counter productive. Just think about it for a minute and you'll see the truth in this. Or sit on your 3-5K$ a year and keep nim from spreading faster. The way to riches is not to put a fence around knowledge.

**Comment by dom96** [comment]
I am the author. And yes, I would love to make it available to everyone. The problem is that I don't fully own the copyright, my publisher does and I don't particularly wish to get sued by them.

Feel free to send them an email, maybe you can convince them?

**Comment by ghost** [comment]
I have an idea to take care of that problem, but it will take some time. Good luck!

**Comment by dom96** [comment]
Interesting. What's your idea?
