### ISSUE TITLE
Listing 7.14 Does Not Compile in Linux

### ISSUE THREAD

**Issue by frkli1965** [dom96/nim-in-action-code#10]
Lines 82 and 84 in database.nim result in compilation errors under Linux!

Line 82 i.e. for i in 0 .. <usernames.len: is a common issue throughout the book and are remedied by removing the white spaces between the '0', '..' and '<' as follows:-
for i in 0..<usernames.len:

Whereas line 84 is simply non-sensical i.e. "if i != <usernames.len:"
I've tried altering to "if i != usernames.len:" and  "if i < usernames.len:", etc. all to no avail as the following runtime error is encountered:-

../Tweeter/tests/database_test.nim(24) database_test
../Tweeter/src/database.nim(84) findMessages
~/.choosenim/toolchains/nim-1.2.6/lib/impure/db_sqlite.nim(257) getAllRows
~/.choosenim/toolchains/nim-1.2.6/lib/impure/db_sqlite.nim(217) setupQuery
~/.choosenim/toolchains/nim-1.2.6/lib/impure/db_sqlite.nim(142) dbError
Error: unhandled exception: near "ORDER": syntax error [DbError]
------------------
(program exited with code: 1)
Press return to continue

Please provide a fix as I actually went to the expense of paying for your book which is a highly unusual requirement to say the least as most programming languages are free to learn these days.

Aside from that, nice book btw albeit somewhat expensive especially considering the erroneous content in a number of places throughout.

**Comment by frkli1965** [comment]
After further deliberation the following re-write to database.nim would suffice:-
.............................................................................................................................
proc findMessages*(database: Database, usernames: seq[string]): seq[Message] =
  result = @[]
    if usernames.len == 0: return
    for i in 0..<usernames.len:
      for row in database.db.fastRows(sql"SELECT username, time, msg FROM Message WHERE username = ?;", usernames[i]):
        result.add(Message(username: row[0], time: fromSeconds(row[1].parseInt), msg: row[2]))
.............................................................................................................................
Tested with additional code in database_test.nim as follows:-
.............................................................................................................................
db.create(User(username: "frkli1965"))
...
db.post(Message(username: "frkli1965", time: getTime() + 4.seconds,
        msg: "Nim in Action has quite a few errors that need addressing!!!"))
...
var frkli: User
doAssert db.findUser("frkli1965", frkli)
...
db.follow(dom, frkli)
...
let messages = db.findMessages(dom.following)
echo(messages)
.............................................................................................................................
VALIDATED OUTPUT >>
.............................................................................................................................
@[(username: "frkli1965", time: 2020-09-30T16:10:19+01:00, msg: "Nim in Action has quite a few errors that need addressing!!!"), (username: "nim_lang", time: 2020-09-30T16:10:11+01:00, msg: "Hello Nim in Action readers"), (username: "nim_lang", time: 2020-09-30T16:10:15+01:00, msg: "99.9% off Nim in Action for everyone, for the next minute only!")]
.............................................................................................................................
Rather than attempt the impossible i.e. expect db_sqlite to unpack the 'usernames' sequence of followers, which ain't ever gonna happen. Sorting and limiting (filtering) of the 'messages' sequence could be enacted retrospectively with Nim code instead.

**Comment by dom96** [comment]
Thank you for reporting this! 

For what it's worth, these procs were correct when the book was written. They were deprecated before 1.0 was released, and then removed in https://github.com/nim-lang/Nim/pull/12535 (starting at version 1.2.0).

You should consider using Nim 1.0.6 to go through the book, you won't have these errors then.

**Comment by dom96** [comment]
Also the Nim repo has this code in its test suite, it was edited for Nim 1.2.0 (sadly) but it gives you an idea on how to fix the code if you want to stick with 1.2.6: https://github.com/nim-lang/Nim/tree/devel/tests/niminaction
